### ISSUE TITLE
Refactoring for ModelProtocol protocol

### ISSUE THREAD

**Issue by hachinobu** [malcommac/FlowKit#3]
Hi, @malcommac 

Thank you for providing a nice library.

Please tell me about the implementation of `ModelProtocol`.

If the object conforms to the `Equatable` protocol, i can use the default implementation of `Extension` so i do not need to write `isEqual` method.

Likewise, if the object conforms to the `Hashable` protocol, i do not want to write the `identifier` property.

Is there a problem with the code below?

```swift

extension ModelProtocol where Self: Hashable {
	
    public var identifier: Int {
        return self.hashValue
    }
    
    //remove code
//    public var hashValue: Int {
//        return self.identifier.hashValue
//    }
	
}

```

It seems that compatibility is good.

[Synthesizing Equatable and Hashable conformance](https://github.com/apple/swift-evolution/blob/master/proposals/0185-synthesize-equatable-hashable.md)

I think that implementation will be easier.

best regards.

**Comment by malcommac** [comment]
Hi, you are correct, `ModelProtocol` is pretty weird yet.
My initial concern is to force the user to adopt this protocol in order to be conform to `Hashable` protocol, used internally to perform diffing between two data reloads.
In fact, actually is a mix of bad practices.
I've tried to refactor it by removing both `isEqual` function and `identifier` variable.
`ModelProtocol` right now must implement only a variable, `hashValue` (the same you need to be `Hashable` conform, even this is a just a repetion). What do think about it?

**Comment by malcommac** [comment]
I've changed partially changed the approach to make it much cleaner.

Each model of the cell must be conform to the `ModelProtocol` protocol.
This protocol require the implementation of a single property called `modelID` (an `Int`) which is used to uniquely identify an object for DeepDiff.

A default implementation of this property is provided via `ObjectIdentifier` for class-based objects (`AnyObject`).
Instead an explicit implementation must be provided for value based objects (for example structs).
